### ISSUE TITLE
Koa2 support

### ISSUE THREAD

**Issue by kristianmandrup** [xpepermint/vue-builder#1]
Hi there,

Really excited about your most recent work. I managed to create a Koa2 compatible version of your express-vue-builder here https://github.com/kristianmandrup/koa-vue-builder/

You are very welcome to mention it as an option on your Readme. 
Perhaps we could collaborate somehow...
Cheers ;)

**Comment by xpepermint** [comment]
This is great! We are headed towards the same goal and cooperation is what makes us human :).

Would you be so kind and split your package into two separated packages as I did in the latest version? The reason for this is to include the [development server](https://github.com/xpepermint/express-vue-dev) only in development and the [bundle renderer](https://github.com/xpepermint/express-vue-builder) only in production.

Please let me know when you do this so I can update the readme files on all related packages.

**Comment by kristianmandrup** [comment]
Cool :) I'm now working on the dev server part.

https://github.com/kristianmandrup/koa-vue-dev

Had problems running `npm i` but it should (hopefully) work

**Comment by kristianmandrup** [comment]
BTW, looks like you forgot to remove the unused `build` dependency in https://github.com/xpepermint/express-vue-builder/blob/master/example/server/middlewares/vue.js

**Comment by xpepermint** [comment]
Fixed, thanks. Can you describe the `npm i` problem? Peer dependencies?

**Comment by kristianmandrup** [comment]
Just temporarily a slow connection for some reason. 

`npm ERR! registry error parsing json`

My `package.json` is valid

**Comment by xpepermint** [comment]
Hum... I remember seeing this once in awhile. I'll take a look.

**Comment by xpepermint** [comment]
Looks ok - I believe it's the ~network issue.

**Comment by xpepermint** [comment]
Hey @kristianmandrup, what's the status of your koa forks?

**Comment by kristianmandrup** [comment]
They should be good. Try yourself ')

**Comment by xpepermint** [comment]
All related readme files have been updated.

**Comment by kristianmandrup** [comment]
Cool :)
